#
# Copyright (c) 2025 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
# Sysbuild config when BLE is disabled: no netcore image (app core only, low power).
# Use with: -DFILE_SUFFIX=ble_disabled
# And for the app: -Dperipheral_power_profiling_dev_OVERLAY_CONFIG=overlay-ble_disabled.conf

SB_CONFIG_APP_POWER_PROFILING_BLE=n
SB_CONFIG_NETCORE_EMPTY=y
